#!/bin/bash
# File              : on-Tv
# License           : MIT
# Author            : Steven Agustinus <steven87.ags@gmail.com>
# Date              : 14.06.2021
# Last Modified Date: 15.06.2021
# Last Modified By  : Steven Agustinus <steven87.ags@gmail.com>
# on-Tv
# Copyright (c) 2021 Steven Agustinus <steven87.ags@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

echo -e '
\e[97m
 =========================================================== \e[0m
\e[31m                                                       
                                ________ __     __         
                               |        \  \   |  \        
        ______  _______         \▓▓▓▓▓▓▓▓ ▓▓   | ▓▓        
       /      \|       \ ______   | ▓▓  | ▓▓   | ▓▓        
      |  ▓▓▓▓▓▓\ ▓▓▓▓▓▓▓\      \  | ▓▓   \▓▓\ /  ▓▓        
      | ▓▓  | ▓▓ ▓▓  | ▓▓\▓▓▓▓▓▓  | ▓▓    \▓▓\  ▓▓         
      | ▓▓__/ ▓▓ ▓▓  | ▓▓         | ▓▓     \▓▓ ▓▓  
       \▓▓    ▓▓ ▓▓  | ▓▓         | ▓▓      \▓▓▓           
        \▓▓▓▓▓▓ \▓▓   \▓▓          \▓▓       \▓   \e[0m    
\e[97m                                                     
                                          
       Author : steven      Find me :  @steven887         
 =========================================================== \e[0m
'                                                           

PLAYER="mpv"

declare -a channelList=(
"ANIMAX         ==>    http://210.210.155.35/session/83bc2526-da69-11e8-881b-c81f66f89318/dr9445/h/h144/01.m3u8"
"ANIPLUS        ==>    http://210.210.155.35/dr9445/h/h02/01.m3u8"
"BERITASATU     ==>    http://edge.linknetott.swiftserve.com/live/BsNew/amlst:beritasatunewsbs/chunklist_b846000.m3u8"
"MNC            ==>    https://iptv-nublltsls-mwafa.vercel.app/api/vidio?id=870"
"TRANS7         ==>    https://video.detik.com/trans7/smil:trans7.smil/playlist.m3u8"
"TRANS-TV       ==>    https://livestreaming-google-etslive.vidio.com/hls-p/ingest_733_720p/index.m3u8"
"NET-TV         ==>    https://livestreaming-google-etslive.vidio.com/hls-p/ingest_875_720p/index.m3u8"
"CNN-INDONESIA  ==>    https://live.cnnindonesia.com/livecnn/smil:cnntv.smil/playlist.m3u8"
"RCTI           ==>    https://livestreaming-google-etslive.vidio.com/hls-p/ingest_665_720p/index.m3u8"
"METROTV-NEWS   ==>    http://edge.metrotvnews.com:1935/live-edge/smil:metro.smil/playlist.m3u8"
"KOMPAS-TV      ==>    https://livestreaming-google-etslive.vidio.com/hls-p/ingest_874_720p/index.m3u8"
"SCTV           ==>    https://livestreaming-google-etslive.vidio.com/hls-p/ingest_204_720p/index.m3u8"
"INDOSIAR       ==>    https://iptvcat.com/my_list/s/3726fa2ed03f6eee3366b7d425b90b45.m3u8"
"GTV            ==>    https://vcdn2.rctiplus.id/live/eds/gtv_fta/live_fta/gtv_fta-avc1_1537200=6-mp4a_64000_eng=2.m3u8"
"ATV            ==>    http://stream1.ninmedia.tv:1935/atv/udp.stream/chunklist_w465987392.m3u8"
"O-CHANNEL      ==>    https://livestreaming-google-etslive.vidio.com/hls-p/ingest_206_720p/index.m3u8"
)

#show the channel list in column format
for i  in "${channelList[@]}" ; do
      keys="${i%% ==>*}"
      vals="${i#* ==>}"
      let idx="${idx}"+1
      echo "$idx> $keys" 
done | pr -T2 

echo -e "\n"

read -p "select your channel (please type: 1,2,3,etc..): " ch

#action to play selected channel
for i  in "${channelList[@]}" ; do
      keys="${i%% ==>*}"
      vals="${i#* ==>}"
      let idx="${idx}"+1
      if [[ "$ch" == "$idx" ]]; then
            echo "$keys now playing please wait.."
            dunstify -t 2000 on-Tv \n$keys
            $PLAYER $vals
      fi
done 

